import type { LogEntry } from '../types';

export const mockLogs: LogEntry[] = [
  {
    id: '1',
    action: 'Admin João Silva apagou relatório semanal.',
    actorName: 'João Silva',
    actorRole: 'super_admin',
    actorId: '101',
    severity: 'critical',
    timestamp: '2024-10-25T09:15:00Z',
    icon: 'delete_forever',
  },
  {
    id: '2',
    action: "Permissões de 'Voluntário' foram alteradas.",
    actorName: 'João Silva',
    actorRole: 'super_admin',
    actorId: '101',
    severity: 'warning',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    icon: 'shield_person',
  },
  {
    id: '3',
    action: 'Sistema IA enviou alerta de contentor cheio.',
    actorName: 'Sistema IA',
    actorRole: 'system',
    actorId: '0',
    severity: 'system',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    icon: 'smart_toy',
  },
  {
    id: '4',
    action: 'Admin João Silva criou nova zona de limpeza.',
    actorName: 'João Silva',
    actorRole: 'admin',
    actorId: '204',
    severity: 'info',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    icon: 'add_location_alt',
  },
  {
    id: '5',
    action: 'Voluntária Maria Pinto acedeu à plataforma.',
    actorName: 'Maria Pinto',
    actorRole: 'volunteer',
    actorId: '512',
    severity: 'info',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    icon: 'login',
  },
  {
    id: '6',
    action: 'Backup automático da base de dados concluído.',
    actorName: 'Sistema',
    actorRole: 'system',
    actorId: '0',
    severity: 'info',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    icon: 'cloud_done',
  },
  {
    id: '7',
    action: 'Tentativa de acesso não autorizado bloqueada.',
    actorName: 'Desconhecido',
    actorRole: 'system',
    actorId: '0',
    severity: 'critical',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    icon: 'security',
  },
  {
    id: '8',
    action: 'Carlos Mendes atualizou perfil de utilizador.',
    actorName: 'Carlos Mendes',
    actorRole: 'admin',
    actorId: '305',
    severity: 'info',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    icon: 'manage_accounts',
  },
  {
    id: '9',
    action: 'Rotas de recolha foram re-otimizadas pela IA.',
    actorName: 'Sistema IA',
    actorRole: 'system',
    actorId: '0',
    severity: 'system',
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    icon: 'alt_route',
  },
  {
    id: '10',
    action: 'Limite de pontos diário excedido — alerta gerado.',
    actorName: 'Sistema',
    actorRole: 'system',
    actorId: '0',
    severity: 'warning',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    icon: 'warning',
  },
];
